spring:
  redis:
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
    sentinel:
      master: mymaster
      nodes: 192.168.228.1:10001,192.168.228.1:10002,192.168.228.1:10003
  datasource:
    　　type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
    　　driver-class-name: org.gjt.mm.mysql.Driver       #配置MySQL的驱动程序类
    　　url: jdbc:mysql://127.0.0.1:3306/high_t_concurrency?useUnicode=true&characterEncoding=utf8
    　　username: root
    　　password: 123456
    　　filters: stat,wall,log4j     #druid监控配置
    　　dbcp2:
      　　min-idle: 5         #数据库连接池的最小维持连接数
      　　initial-size: 5     #初始化提供的连接数
      　　max-total: 2000          #最大的连接数
      　　max-wait-millis: 200        #等待连接获取的最大超时时间
server:
  port: 9527
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml
